cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
file:
  upload-dir: /home/lucas/uploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  application:
    name: bookstore-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  servelt:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    br.com.sousinhacode: debug
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true

